<a href="https://colab.research.google.com/github/AlanGomes107/Py/blob/main/Python_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Condicionais***

In [1]:
temperatura = 35

if (temperatura > 30):
    print('Hoje está muito quente!')

Hoje está muito quente!


In [2]:
temperatura = 25

if (temperatura > 30):
    print('Hoje está muito quente!')

In [3]:
temperatura = 25

if (temperatura > 30):
    print('Hoje está muito quente!')
else:
    print('A temperatura está agradável!')

A temperatura está agradável!


In [4]:
temperatura = 25

if (temperatura > 30):
    print('Hoje está muito quente!')
elif (temperatura > 25):
    print('A temperatura está agradável!')
elif (temperatura > 15):
    print('O tempo está mudando!')
else:
    print('Que friaca!')

O tempo está mudando!


In [5]:
temperatura = 25

if (temperatura > 30):
    print('Hoje está muito quente!')
elif (temperatura >= 25):
    print('A temperatura está agradável!')
elif (temperatura > 15):
    print('O tempo está mudando!')
else:
    print('Que friaca!')

A temperatura está agradável!


# ***Estruturas de repetição - For***


In [6]:
frutas = ['abacate', 'pera', 'abacaxi']

for elemento in frutas:
    print(elemento)

abacate
pera
abacaxi


In [8]:
frutas = ['abacate', 'pera', 'abacaxi']

for elemento in frutas:
    if elemento.startswith('a'):
        print(elemento)

abacate
abacaxi


In [9]:
lista_num = [1,2,3,4,5]
soma = 0

for numero in lista_num:
    soma = soma + numero
    print(soma)

1
3
6
10
15


In [10]:
lista_num = [1,2,3,4,5]
soma = 0

for numero in lista_num:
    soma = soma + numero
print(soma)

15


# *While*

In [11]:
condicao = 1
soma = 0

while condicao <= 5:
    soma = soma + condicao
    condicao = condicao + 1
    print(soma)

1
3
6
10
15


In [12]:
condicao = 1
soma = 0

while condicao <= 5:
    soma = soma + condicao
    condicao = condicao + 1
    print(condicao)
    break

2


# ***Numpy***

In [13]:
import numpy as np

In [14]:
np.array([1,2,3])

array([1, 2, 3])

In [15]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [17]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.shape

(2, 2, 3)

In [20]:
b = np.array([[1,2,3],[4,5,6]])

In [21]:
b.shape

(2, 3)

In [22]:
len(a)

2

In [23]:
len(b)

2

In [24]:
a.ndim

3

In [25]:
b.ndim

2

In [26]:
a.size

12

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b2 = b.reshape(-1,1)

In [29]:
b2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
b

array([[1, 2],
       [3, 4]])

In [34]:
a > b

array([[False, False],
       [False, False]])

In [35]:
a < b

array([[False, False],
       [False, False]])

In [36]:
a == b

array([[ True,  True],
       [ True,  True]])

In [39]:
a != b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


True

# ***Concatenação***

In [40]:
a = np.array([1,2])
b = np.array([3,4,5,6])
c = np.array([7,8,9])

In [41]:
a

array([1, 2])

In [42]:
b

array([3, 4, 5, 6])

In [43]:
c

array([7, 8, 9])

In [44]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [45]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [46]:
a

array([[1, 2],
       [3, 4]])

In [47]:
b

array([[5, 6],
       [7, 8]])

In [48]:
np.concatenate([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [50]:
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate([a,b], axis=1)
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
a = np.array ([1,2,3,4])
b = np.array ([5,6,7,8])

In [53]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
##fim